[package]
name = "cw20-stake"
authors = ["Ben2x4 <Ben2x4@tutanota.com>"]
description = "CW20 token that can be staked and staked balance can be queried at any height"
edition = "2018"
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
# cosmwasm-storage = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-hooks = { workspace = true }
thiserror = { workspace = true }
cw-paginate-storage = { workspace = true }
cw-ownable = { workspace = true }
dao-hooks = { workspace = true }
dao-voting = { workspace = true }

# cw20-stake-v1 = { workspace = true, features = ["library"] }
# cw-utils-v1 = { workspace = true }

secret-utils = { workspace = true }
cosmwasm-std ={ workspace = true }
secret-cosmwasm-storage={ workspace = true }
secret-toolkit = { workspace = true }
secret-storage-plus = { workspace = true }
secret-cw-controllers = { workspace = true }
secret-cw2 = { workspace = true }

subtle = { version = "2.2.3", default-features = false }
base64 = "0.12.3"
hex = "0.4.2"
sha2 = { version = "0.9.1", default-features = false }
snafu = { version = "0.6.3" }

[dev-dependencies]
secret-multi-test = { workspace = true }
anyhow = { workspace = true }
