[package]
name = "dao-interface"
authors = ["ekez ekez@withoutdoing.com"]
description = "A package containing interface definitions for DAO DAO DAOs."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std ={ workspace = true }
cosmwasm-schema = { workspace = true }
secret-cw2 = { workspace = true }
secret-toolkit = { workspace = true }
# cw721 = { workspace = true }
cw-hooks = { workspace = true }
secret-utils = { workspace = true }
osmosis-std = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
