[package]
name = "secret-cw2"
version = "1.0.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Definition and types for the CosmWasm-2 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cosmwasm-std = {workspace=true}
cosmwasm-schema = "1.1.5"
utils = { package = "secret-utils", path = "../utils/" }
cw-storage-plus = { package = "secret-storage-plus", path = "../storage-plus/" }
schemars = "0.8.1"
serde = { version = "1.0.1", default-features = false, features = ["derive"] }
