[package]
name = "secret-cw2"
version = "1.0.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Definition and types for the CosmWasm-2 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cosmwasm-std = {workspace=true}
cosmwasm-schema = {workspace=true}
secret-utils ={workspace=true}
secret-storage-plus = { workspace = true}
schemars = {workspace=true}
serde = {workspace=true}