[package]
name = "cw-vesting"
authors = ["Jake Hartnell", "ekez <ekez@withoutdoing.com>", "blue-note"]
description = "A CosmWasm vesting contract."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true}
cw-denom = { workspace = true }
cw-ownable = { workspace = true }
cw-paginate-storage = { workspace = true }
cw-stake-tracker = { workspace = true }
secret-storage-plus = { workspace = true }
secret-utils = { workspace = true }
cw-wormhole = { workspace = true }
secret-cw2 = { workspace = true }
secret-toolkit = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wynd-utils = { workspace = true }
snip20-reference-impl = { workspace = true }


[dev-dependencies]
anyhow = { workspace = true }
secret-multi-test = { workspace = true }
snip20-reference-impl = { workspace = true }
# dao-testing = { workspace = true }
